package com.kozimor.wms.IntegrationTests;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.domain.Page;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import com.kozimor.wms.Database.Model.Category;
import com.kozimor.wms.Database.Model.Item;
import com.kozimor.wms.Database.Model.ItemType;
import com.kozimor.wms.Database.Model.UnitType;
import com.kozimor.wms.Database.Repository.CategoryRepository;
import com.kozimor.wms.Database.Repository.ItemRepository;
import com.kozimor.wms.Database.Service.ItemService;

@SpringBootTest
@ActiveProfiles("test")
@Transactional
@DisplayName("ItemServiceImpl - Integration Tests with Search")
class ItemServiceIntegrationTest {

    @Autowired
    private ItemService itemService;

    @Autowired
    private ItemRepository itemRepository;

    @Autowired
    private CategoryRepository categoryRepository;

    private Item testItem;
    private Category testCategory;
    private Category category2;

    @BeforeEach
    void setUp() {
        // Create test categories
        testCategory = Category.builder()
                .name("Electronics")
                .description("Electronic components")
                .build();
        testCategory = categoryRepository.save(testCategory);

        category2 = Category.builder()
                .name("Mechanical")
                .description("Mechanical parts")
                .build();
        category2 = categoryRepository.save(category2);

        // Create test item
        testItem = new Item();
        testItem.setName("Integration Test Item");
        testItem.setDescription("Test item for integration tests");
        testItem.setCategory(testCategory);
        testItem.setCurrentQuantity(100.0);
        testItem.setUnit(UnitType.PCS);
        testItem.setType(ItemType.PRODUCT);
    }

    // ========== CRITICAL CRUD OPERATIONS ==========

    @Test
    @DisplayName("Should create item with auto-generated QR code")
    void testCreateItemWithAutoGeneratedQrCode() {
        Item result = itemService.createItem(testItem);

        assertNotNull(result.getId());
        assertNotNull(result.getQrCode());
        assertFalse(result.getQrCode().isBlank());
    }

    @Test
    @DisplayName("Should retrieve item by ID from database")
    void testGetItemById() {
        Item savedItem = itemService.createItem(testItem);

        Optional<Item> result = itemService.getItemById(savedItem.getId());

        assertTrue(result.isPresent());
        assertEquals("Integration Test Item", result.get().getName());
        assertEquals(100.0, result.get().getCurrentQuantity());
    }

    @Test
    @DisplayName("Should retrieve item by QR code from database")
    void testGetItemByQrCode() {
        Item savedItem = itemService.createItem(testItem);

        Optional<Item> result = itemService.getItemByQrCode(savedItem.getQrCode());

        assertTrue(result.isPresent());
        assertEquals("Integration Test Item", result.get().getName());
    }

    @Test
    @DisplayName("Should return empty Optional when item not found by ID")
    void testGetItemByIdNotFound() {
        Optional<Item> result = itemService.getItemById(999999L);

        assertFalse(result.isPresent());
    }

    @Test
    @DisplayName("Should update item successfully")
    void testUpdateItem() {
        Item savedItem = itemService.createItem(testItem);
        Item updateData = new Item();
        updateData.setName("Updated Item Name");
        updateData.setDescription("Updated description");
        updateData.setCurrentQuantity(150.0);
        updateData.setUnit(UnitType.KG);
        updateData.setCategory(testCategory);

        Item result = itemService.updateItem(savedItem.getId(), updateData);

        assertEquals("Updated Item Name", result.getName());
        assertEquals(250.0, result.getCurrentQuantity());
        assertEquals(UnitType.KG, result.getUnit());
    }

    @Test
    @DisplayName("Should delete item successfully")
    void testDeleteItem() {
        Item savedItem = itemService.createItem(testItem);
        assertTrue(itemRepository.existsById(savedItem.getId()));

        itemService.deleteItem(savedItem.getId());

        assertFalse(itemRepository.existsById(savedItem.getId()));
    }

    // ========== CRITICAL SEARCH TESTS ==========

    @Test
    @DisplayName("Should search items by type - PRODUCT")
    void testSearchItemsByType() {
        // Arrange
        Item item1 = new Item();
        item1.setName("Component 1");
        item1.setCategory(testCategory);
        item1.setCurrentQuantity(50.0);
        item1.setUnit(UnitType.PCS);
        item1.setType(ItemType.PRODUCT);
        itemService.createItem(item1);

        Item item2 = new Item();
        item2.setName("Component 2");
        item2.setCategory(testCategory);
        item2.setCurrentQuantity(30.0);
        item2.setUnit(UnitType.PCS);
        item2.setType(ItemType.COMPONENT);
        itemService.createItem(item2);

        // Act
        Page<?> results = (Page<?>) itemService.searchItems(
                ItemType.PRODUCT.toString(), null, null, null, null, null, 0, 10);

        // Assert
        assertTrue(results.getTotalElements() > 0);
    }

    @Test
    @DisplayName("Should search items by category ID")
    void testSearchItemsByCategory() {
        // Arrange
        Item item1 = new Item();
        item1.setName("Electronic Item");
        item1.setCategory(testCategory);
        item1.setCurrentQuantity(100.0);
        item1.setUnit(UnitType.PCS);
        item1.setType(ItemType.PRODUCT);
        itemService.createItem(item1);

        Item item2 = new Item();
        item2.setName("Mechanical Item");
        item2.setCategory(category2);
        item2.setCurrentQuantity(50.0);
        item2.setUnit(UnitType.PCS);
        item2.setType(ItemType.PRODUCT);
        itemService.createItem(item2);

        // Act
        Page<?> results = (Page<?>) itemService.searchItems(
                null, testCategory.getId(), null, null, null, null, 0, 10);

        // Assert
        assertTrue(results.getTotalElements() > 0);
    }

    @Test
    @DisplayName("Should search items by unit type")
    void testSearchItemsByUnit() {
        // Arrange
        Item item1 = new Item();
        item1.setName("PCS Item");
        item1.setCategory(testCategory);
        item1.setCurrentQuantity(100.0);
        item1.setUnit(UnitType.PCS);
        item1.setType(ItemType.PRODUCT);
        itemService.createItem(item1);

        Item item2 = new Item();
        item2.setName("KG Item");
        item2.setCategory(testCategory);
        item2.setCurrentQuantity(50.0);
        item2.setUnit(UnitType.KG);
        item2.setType(ItemType.PRODUCT);
        itemService.createItem(item2);

        // Act
        Page<?> results = (Page<?>) itemService.searchItems(
                null, null, UnitType.PCS.toString(), null, null, null, 0, 10);

        // Assert
        assertTrue(results.getTotalElements() > 0);
    }

    @Test
    @DisplayName("Should search items by quantity range - min quantity")
    void testSearchItemsByMinQuantity() {
        // Arrange
        Item item1 = new Item();
        item1.setName("High Quantity Item");
        item1.setCategory(testCategory);
        item1.setCurrentQuantity(100.0);
        item1.setUnit(UnitType.PCS);
        item1.setType(ItemType.PRODUCT);
        itemService.createItem(item1);

        Item item2 = new Item();
        item2.setName("Low Quantity Item");
        item2.setCategory(testCategory);
        item2.setCurrentQuantity(5.0);
        item2.setUnit(UnitType.PCS);
        item2.setType(ItemType.PRODUCT);
        itemService.createItem(item2);

        // Act
        Page<?> results = (Page<?>) itemService.searchItems(
                null, null, null, 50, null, null, 0, 10);

        // Assert
        assertTrue(results.getTotalElements() > 0);
    }

    @Test
    @DisplayName("Should search items by quantity range - max quantity")
    void testSearchItemsByMaxQuantity() {
        // Arrange
        Item item1 = new Item();
        item1.setName("High Quantity Item");
        item1.setCategory(testCategory);
        item1.setCurrentQuantity(200.0);
        item1.setUnit(UnitType.PCS);
        item1.setType(ItemType.PRODUCT);
        itemService.createItem(item1);

        Item item2 = new Item();
        item2.setName("Low Quantity Item");
        item2.setCategory(testCategory);
        item2.setCurrentQuantity(30.0);
        item2.setUnit(UnitType.PCS);
        item2.setType(ItemType.PRODUCT);
        itemService.createItem(item2);

        // Act
        Page<?> results = (Page<?>) itemService.searchItems(
                null, null, null, null, 100, null, 0, 10);

        // Assert
        assertTrue(results.getTotalElements() > 0);
    }

    @Test
    @DisplayName("Should search items by quantity range - both min and max")
    void testSearchItemsByQuantityRange() {
        // Arrange
        Item item1 = new Item();
        item1.setName("In Range Item");
        item1.setCategory(testCategory);
        item1.setCurrentQuantity(75.0);
        item1.setUnit(UnitType.PCS);
        item1.setType(ItemType.PRODUCT);
        itemService.createItem(item1);

        Item item2 = new Item();
        item2.setName("Out of Range Item");
        item2.setCategory(testCategory);
        item2.setCurrentQuantity(150.0);
        item2.setUnit(UnitType.PCS);
        item2.setType(ItemType.PRODUCT);
        itemService.createItem(item2);

        // Act
        Page<?> results = (Page<?>) itemService.searchItems(
                null, null, null, 50, 100, null, 0, 10);

        // Assert
        assertTrue(results.getTotalElements() > 0);
    }

    @Test
    @DisplayName("Should search items by name")
    void testSearchItemsByName() {
        // Arrange
        Item item1 = new Item();
        item1.setName("SearchableItem");
        item1.setCategory(testCategory);
        item1.setCurrentQuantity(100.0);
        item1.setUnit(UnitType.PCS);
        item1.setType(ItemType.PRODUCT);
        itemService.createItem(item1);

        // Act
        Page<?> results = (Page<?>) itemService.searchItemsByName("Searchable", 0, 10);

        // Assert
        assertTrue(results.getTotalElements() > 0);
    }

    @Test
    @DisplayName("Should search items with multiple criteria combined")
    void testSearchItemsWithMultipleCriteria() {
        // Arrange
        Item item1 = new Item();
        item1.setName("Matching Item");
        item1.setCategory(testCategory);
        item1.setCurrentQuantity(75.0);
        item1.setUnit(UnitType.PCS);
        item1.setType(ItemType.PRODUCT);
        itemService.createItem(item1);

        Item item2 = new Item();
        item2.setName("Non-matching Item");
        item2.setCategory(category2);
        item2.setCurrentQuantity(150.0);
        item2.setUnit(UnitType.KG);
        item2.setType(ItemType.COMPONENT);
        itemService.createItem(item2);

        // Act
        Page<?> results = (Page<?>) itemService.searchItems(
                ItemType.PRODUCT.toString(),
                testCategory.getId(),
                UnitType.PCS.toString(),
                50,
                100,
                null,
                0,
                10);

        // Assert
        assertTrue(results.getTotalElements() > 0);
    }

    @Test
    @DisplayName("Should return empty page when search criteria matches nothing")
    void testSearchWithNoMatches() {
        // Act
        Page<?> results = (Page<?>) itemService.searchItems(
                ItemType.COMPONENT.toString(),
                category2.getId(),
                UnitType.LITER.toString(),
                1000,
                2000,
                null,
                0,
                10);

        // Assert
        assertEquals(0, results.getTotalElements());
    }

    // ========== PAGINATION TESTS ==========

    @Test
    @DisplayName("Should handle pagination in search results")
    void testSearchPagination() {
        // Create multiple items
        for (int i = 0; i < 15; i++) {
            Item item = new Item();
            item.setName("Item " + i);
            item.setCategory(testCategory);
            item.setCurrentQuantity(100.0 + i);
            item.setUnit(UnitType.PCS);
            item.setType(ItemType.PRODUCT);
            itemService.createItem(item);
        }

        // Act - first page
        Page<?> page1 = (Page<?>) itemService.searchItems(
                null, null, null, null, null, null, 0, 5);

        // Act - second page
        Page<?> page2 = (Page<?>) itemService.searchItems(
                null, null, null, null, null, null, 1, 5);

        // Assert
        assertEquals(5, page1.getContent().size());
        assertEquals(5, page2.getContent().size());
        assertTrue(page1.getTotalElements() >= 15);
    }

    // ========== DATABASE CONSISTENCY TESTS ==========

    @Test
    @DisplayName("Should preserve QR code when updating item")
    void testUpdateItemPreservesQrCode() {
        Item savedItem = itemService.createItem(testItem);
        String originalQrCode = savedItem.getQrCode();
        Item updateData = new Item();
        updateData.setName("New Name");
        updateData.setDescription("New description");
        updateData.setCurrentQuantity(150.0);
        updateData.setUnit(UnitType.PCS);
        updateData.setCategory(testCategory);

        Item result = itemService.updateItem(savedItem.getId(), updateData);

        assertEquals(originalQrCode, result.getQrCode());
    }

    @Test
    @DisplayName("Should throw exception when updating non-existent item")
    void testUpdateNonExistentItem() {
        assertThrows(Exception.class,
                () -> itemService.updateItem(999999L, testItem));
    }

    @Test
    @DisplayName("Should throw exception when deleting non-existent item")
    void testDeleteNonExistentItem() {
        assertThrows(Exception.class,
                () -> itemService.deleteItem(999999L));
    }
}
