package com.kozimor.wms.IntegrationTests;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import com.kozimor.wms.Database.Model.Category;
import com.kozimor.wms.Database.Model.Item;
import com.kozimor.wms.Database.Model.ItemType;
import com.kozimor.wms.Database.Model.UnitType;
import com.kozimor.wms.Database.Repository.CategoryRepository;
import com.kozimor.wms.Database.Repository.ItemRepository;
import com.kozimor.wms.Database.Service.ItemService;

@SpringBootTest
@ActiveProfiles("test")
@Transactional
@DisplayName("ItemServiceImpl - Integration Tests")
class ItemServiceIntegrationTest {

    @Autowired
    private ItemService itemService;

    @Autowired
    private ItemRepository itemRepository;

    @Autowired
    private CategoryRepository categoryRepository;

    private Item testItem;
    private Category testCategory;

    @BeforeEach
    void setUp() {
        // Create test category
        testCategory = Category.builder()
                .name("Test Category")
                .description("Category for integration tests")
                .build();
        testCategory = categoryRepository.save(testCategory);

        // Create test item
        testItem = new Item();
        testItem.setName("Integration Test Item");
        testItem.setDescription("Test item for integration tests");
        testItem.setCategory(testCategory);
        testItem.setCurrentQuantity(100);
        testItem.setUnit(UnitType.PCS);
        testItem.setType(ItemType.PRODUCT);
    }

    // ========== CREATE ITEM TESTS ==========

    @Test
    @DisplayName("Should create item with auto-generated QR code")
    void testCreateItemWithAutoGeneratedQrCode() {
        // Act
        Item result = itemService.createItem(testItem);

        // Assert
        assertNotNull(result.getId());
        assertNotNull(result.getQrCode());
        assertFalse(result.getQrCode().isBlank());
    }

    @Test
    @DisplayName("Should create item with provided QR code")
    void testCreateItemWithProvidedQrCode() {
        // Arrange
        testItem.setQrCode("CUSTOM_QR_001");

        // Act
        Item result = itemService.createItem(testItem);

        // Assert
        assertNotNull(result.getId());
        assertTrue(result.getQrCode().contains("CUSTOM_QR_001"));
    }

    @Test
    @DisplayName("Should create item and persist to database")
    void testCreateItemPersistsToDB() {
        // Act
        Item result = itemService.createItem(testItem);

        // Assert
        assertTrue(itemRepository.existsById(result.getId()));
        Optional<Item> found = itemRepository.findById(result.getId());
        assertTrue(found.isPresent());
        assertEquals("Integration Test Item", found.get().getName());
    }

    // ========== GET ITEM TESTS ==========

    @Test
    @DisplayName("Should retrieve item by ID from database")
    void testGetItemById() {
        // Arrange
        Item savedItem = itemService.createItem(testItem);

        // Act
        Optional<Item> result = itemService.getItemById(savedItem.getId());

        // Assert
        assertTrue(result.isPresent());
        assertEquals("Integration Test Item", result.get().getName());
        assertEquals(100, result.get().getCurrentQuantity());
    }

    @Test
    @DisplayName("Should retrieve item by QR code from database")
    void testGetItemByQrCode() {
        // Arrange
        Item savedItem = itemService.createItem(testItem);

        // Act
        Optional<Item> result = itemService.getItemByQrCode(savedItem.getQrCode());

        // Assert
        assertTrue(result.isPresent());
        assertEquals("Integration Test Item", result.get().getName());
    }

    @Test
    @DisplayName("Should return empty Optional when item not found by ID")
    void testGetItemByIdNotFound() {
        // Act
        Optional<Item> result = itemService.getItemById(999999L);

        // Assert
        assertFalse(result.isPresent());
    }

    @Test
    @DisplayName("Should return empty Optional when item not found by QR code")
    void testGetItemByQrCodeNotFound() {
        // Act
        Optional<Item> result = itemService.getItemByQrCode("NONEXISTENT_QR");

        // Assert
        assertFalse(result.isPresent());
    }

    // ========== UPDATE ITEM TESTS ==========

    @Test
    @DisplayName("Should update item successfully")
    void testUpdateItem() {
        // Arrange
        Item savedItem = itemService.createItem(testItem);
        Item updateData = new Item();
        updateData.setName("Updated Item Name");
        updateData.setDescription("Updated description");
        updateData.setCurrentQuantity(250);
        updateData.setUnit(UnitType.KG);
        updateData.setCategory(testCategory);

        // Act
        Item result = itemService.updateItem(savedItem.getId(), updateData);

        // Assert
        assertEquals("Updated Item Name", result.getName());
        assertEquals("Updated description", result.getDescription());
        assertEquals(250, result.getCurrentQuantity());
        assertEquals(UnitType.KG, result.getUnit());
    }

    @Test
    @DisplayName("Should preserve QR code when updating item")
    void testUpdateItemPreservesQrCode() {
        // Arrange
        Item savedItem = itemService.createItem(testItem);
        String originalQrCode = savedItem.getQrCode();
        Item updateData = new Item();
        updateData.setName("New Name");
        updateData.setDescription("New description");
        updateData.setCurrentQuantity(150);
        updateData.setUnit(UnitType.PCS);
        updateData.setCategory(testCategory);

        // Act
        Item result = itemService.updateItem(savedItem.getId(), updateData);

        // Assert
        assertEquals(originalQrCode, result.getQrCode());
    }

    @Test
    @DisplayName("Should throw exception when updating non-existent item")
    void testUpdateNonExistentItem() {
        // Act & Assert
        assertThrows(Exception.class,
                () -> itemService.updateItem(999999L, testItem));
    }

    // ========== DELETE ITEM TESTS ==========

    @Test
    @DisplayName("Should delete item successfully")
    void testDeleteItem() {
        // Arrange
        Item savedItem = itemService.createItem(testItem);
        assertTrue(itemRepository.existsById(savedItem.getId()));

        // Act
        itemService.deleteItem(savedItem.getId());

        // Assert
        assertFalse(itemRepository.existsById(savedItem.getId()));
    }

    @Test
    @DisplayName("Should throw exception when deleting non-existent item")
    void testDeleteNonExistentItem() {
        // Act & Assert
        assertThrows(Exception.class,
                () -> itemService.deleteItem(999999L));
    }

    // ========== GET ALL ITEMS TESTS ==========

    @Test
    @DisplayName("Should retrieve all items from database")
    void testGetAllItems() {
        // Arrange
        long initialCount = itemRepository.count();
        itemService.createItem(testItem);

        // Act
        var result = itemService.getAllItems();

        // Assert
        assertEquals(initialCount + 1, result.size());
    }

    // ========== ITEM COUNT TESTS ==========

    @Test
    @DisplayName("Should return correct item count")
    void testGetItemCount() {
        // Arrange
        long initialCount = itemRepository.count();
        itemService.createItem(testItem);

        // Act
        long newCount = itemRepository.count();

        // Assert
        assertEquals(initialCount + 1, newCount);
    }

    // ========== DATABASE CONSISTENCY TESTS ==========

    @Test
    @DisplayName("Should maintain database consistency - changes rolled back after test")
    void testDatabaseConsistency() {
        // Arrange
        long countBefore = itemRepository.count();

        // Act
        itemService.createItem(testItem);
        long countAfter = itemRepository.count();

        // Assert
        assertEquals(countBefore + 1, countAfter);
        // After test completes, @Transactional will rollback changes
        // Database will be restored to original state
    }

    @Test
    @DisplayName("Should handle item with null optional fields")
    void testCreateItemWithNullOptionalFields() {
        // Arrange
        testItem.setDescription(null);

        // Act
        Item result = itemService.createItem(testItem);

        // Assert
        assertNotNull(result.getId());
        assertNull(result.getDescription());
    }

    @Test
    @DisplayName("Should update item quantity without affecting category")
    void testUpdateItemQuantityOnlyAffectsQuantity() {
        // Arrange
        Item savedItem = itemService.createItem(testItem);
        Category originalCategory = savedItem.getCategory();
        Item updateData = new Item();
        updateData.setName("Same Name");
        updateData.setDescription("Same description");
        updateData.setCurrentQuantity(500);
        updateData.setUnit(UnitType.PCS);
        updateData.setCategory(testCategory);

        // Act
        Item result = itemService.updateItem(savedItem.getId(), updateData);

        // Assert
        assertEquals(500, result.getCurrentQuantity());
        assertEquals(originalCategory.getId(), result.getCategory().getId());
    }
}
